#!/bin/bash
set -e

export HOOKS_DIR=$( cd "$( dirname "$0" )" && pwd)

#Add the Ruby2 PPA to satisfy Errbit dependencies
# Referenced: http://askubuntu.com/questions/261329/package-for-ruby-2-0-on-precise
add-apt-repository -y ppa:brightbox/ruby-ng-experimental

apt-get update

apt-get install -y \
  ruby2.0 ruby2.0-dev \
  build-essential libssl-dev zlib1g-dev

gem install bundler --no-rdoc --no-ri

cd "$(dirname $0)" && bundle install

mkdir -p /etc/chef

cat > /etc/chef/solo.rb <<EOF
cookbook_path '$HOOKS_DIR/cookbooks'
EOF