#!/bin/bash
set -e

DEBUG=`config-get debug`

HOOK_NAME=$(basename $0)
CHARM_NAME=errbit

if [[ "$HOOK_NAME" == *-relation-* ]]; then
  COOKBOOK_NAME="${HOOK_NAME%-relation*}-relation"
  RECIPE_NAME=${HOOK_NAME#*relation-}
else
  COOKBOOK_NAME=$CHARM_NAME
  RECIPE_NAME=$HOOK_NAME
fi

#todo remove debug logging
if [ $DEBUG = "true" ]; then
  cd "$(dirname $0)" && bundle exec chef-solo -l debug -o "recipe[$COOKBOOK_NAME::$RECIPE_NAME]"
else
  cd "$(dirname $0)" && bundle exec chef-solo -o "recipe[$COOKBOOK_NAME::$RECIPE_NAME]"
fi
